### ISSUE TITLE
Less traitors than expected

### ISSUE THREAD

**Issue by Maksimo007** [lzinga/TTTWeightedTraitorSelection#3] opened 2016-02-05 19:34 UTC
Hello,
the script is very nice but there is one bug:
Sometimes only 1 traitor is selected instead of 2 (also detective). It would be nice if you could fix it. :)

Maksimo007

**Comment by lzinga** [comment] 2016-02-07 23:43
This is a duplicate of #1

I have looked at this issue but haven't ever really been able to find the reasoning behind it. If anyone has any suggestions feel free to let me know.

**Closed as completed** 2016-08-26 03:34 UTC
Labels: duplicate
